import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/developer-pic-12.png";
import AnimatedText from '@/components/AnimatedText';
import Link from "next/link";
import { LinkArrow } from '@/components/Icons'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className="flex gap-10 item-center justify-between w-full">
            <div className='w-1/2'>
              <Image src={profilePic} alt="devChukz" className='w-full h-auto'/>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Hi, i'm Anigara Maduabuchukwu" className='!text-5xl !text-left'/>
              <p className='my-4 text-base font-medium'>
                I am committed to transforming concepts into cutting-edge web applications as an accomplished front-end developer. View my most recent works demonstrating my React.js and web development expertise.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href="/dummy.pdf" target={"_blank"}
                className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark'
                download={true}
                >Resume <LinkArrow className={"w-6 ml-1"}/>
                </Link>
                
                <Link href="mailto:anigaramadu@gmail.com" target={"_blank"}
                className='ml-4 text-lg font-medium capitalize text-dark underline'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
};
